clear
pkg update && pkg upgrade
pkg install python
pkg install python2
pkg install git
pkg install curl
pkg install php
pkg install toilet
pkg install figlet
pip install request
pip2 install request
pkg install request
pkg install nano
pip install bs4
pkg install gem
pkg install ruby
gem install lolcat
pkg install mechanize
pip install mechanize
pip2 install mechanize
pkg install vim
pkg install openssh
pkg install fish
pkg install clang
pkg install gnupg
pkg install wget
pkg install neofetch
pkg install screenfetch
pkg install unzip
pkg install termcolor
